"""sync_order_models_and_tables

Revision ID: 97efa9608e73
Revises: 68fb34f50033
Create Date: 2026-07-17 19:36:09.532270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97efa9608e73'
down_revision: Union[str, Sequence[str], None] = '68fb34f50033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('house', sa.String(length=255), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('pincode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.add_column('orders', sa.Column('message_id', sa.String(length=255), nullable=False))
    op.add_column('orders', sa.Column('provider_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('provider_name', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('state', sa.String(length=50), nullable=False))
    op.add_column('orders', sa.Column('amount', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('currency', sa.String(length=10), nullable=False))
    op.add_column('orders', sa.Column('raw_response', sa.JSON(), nullable=True))
    op.alter_column('orders', 'transaction_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'items')
    op.drop_column('orders', 'total_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.alter_column('orders', 'transaction_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('orders', 'raw_response')
    op.drop_column('orders', 'currency')
    op.drop_column('orders', 'amount')
    op.drop_column('orders', 'state')
    op.drop_column('orders', 'provider_name')
    op.drop_column('orders', 'provider_id')
    op.drop_column('orders', 'message_id')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
